"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['nest.py']
DATA_FILES = []

OPTIONS = {
    'iconfile':'resources/Nest.icns',
    'plist':'resources/Info.plist'
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    version='0.0.1',
    author='Andrew Murray',
    setup_requires=['py2app'],
)
